I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 129, in script
    python:
  File "game/script.rpy", line 143, in <module>
    resp2 = urllib.urlopen(url2)
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 129, in script
    python:
  File "renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 143, in <module>
    resp2 = urllib.urlopen(url2)
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/urllib.py", line 87, in urlopen
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/urllib.py", line 215, in open
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/urllib.py", line 445, in open_https
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/httplib.py", line 1078, in endheaders
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/httplib.py", line 894, in _send_output
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/httplib.py", line 856, in send
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/httplib.py", line 1303, in connect
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/ssl.py", line 369, in wrap_socket
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/ssl.py", line 599, in __init__
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/ssl.py", line 828, in do_handshake
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)

Windows-10-10.0.19041
Ren'Py 7.4.2.1292
MySQLTest 1.0
Fri Mar 12 23:28:25 2021
