I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 124, in script
    e "it didn't work"
Exception: Possible infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 124, in script
    e "it didn't work"
  File "C:\Users\rodri\Desktop\renpy-7.2.2-sdk\renpy\execution.py", line 59, in check_infinite_loop
    raise Exception("Possible infinite loop.")
Exception: Possible infinite loop.

Windows-8-6.2.9200
Ren'Py 7.3.0.271
MySQLTest 1.0
Mon Aug 05 18:47:37 2019
